// front/example/lingnote_front/components/note-editor.tsx
"use client"

import { useState, useEffect, useCallback, useRef } from "react"
import { cn } from "@/lib/utils"
import { Textarea } from "@/components/ui/textarea"

interface NoteEditorProps {
  title: string
  content: string
  onTitleChange: (title: string) => void
  onContentChange: (content: string) => void
  isSaving: boolean
  lastSavedAt?: Date
}

export function NoteEditor({
  title,
  content,
  onTitleChange,
  onContentChange,
  isSaving,
  lastSavedAt,
}: NoteEditorProps) {
  const titleRef = useRef<HTMLTextAreaElement>(null)
  const contentRef = useRef<HTMLTextAreaElement>(null)

  // Auto-resize title textarea
  const adjustTitleHeight = useCallback(() => {
    const textarea = titleRef.current
    if (textarea) {
      textarea.style.height = "auto"
      textarea.style.height = `${textarea.scrollHeight}px`
    }
  }, [])

  // Auto-resize content textarea
  const adjustContentHeight = useCallback(() => {
    const textarea = contentRef.current
    if (textarea) {
      textarea.style.height = "auto"
      const newHeight = Math.max(textarea.scrollHeight, 400)
      textarea.style.height = `${newHeight}px`
    }
  }, [])

  useEffect(() => {
    adjustTitleHeight()
  }, [title, adjustTitleHeight])

  useEffect(() => {
    adjustContentHeight()
  }, [content, adjustContentHeight])

  const handleTitleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onTitleChange(e.target.value)
  }

  const handleContentChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    onContentChange(e.target.value)
  }

  const handleTitleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter") {
      e.preventDefault()
      contentRef.current?.focus()
    }
  }

  const formatLastSaved = (date: Date) => {
    const now = new Date()
    const diff = now.getTime() - date.getTime()
    const seconds = Math.floor(diff / 1000)
    const minutes = Math.floor(seconds / 60)
    const hours = Math.floor(minutes / 60)

    if (seconds < 10) return "刚刚保存"
    if (seconds < 60) return `${seconds} 秒前保存`
    if (minutes < 60) return `${minutes} 分钟前保存`
    if (hours < 24) return `${hours} 小时前保存`
    return date.toLocaleDateString("zh-CN", {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    })
  }

  return (
    <div className="flex h-full flex-col">
      {/* Save Status */}
      <div className="flex h-10 items-center justify-end px-8">
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          {isSaving ? (
            <>
              <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-primary" />
              <span>保存中...</span>
            </>
          ) : lastSavedAt ? (
            <>
              <span className="h-1.5 w-1.5 rounded-full bg-green-500" />
              <span>{formatLastSaved(lastSavedAt)}</span>
            </>
          ) : null}
        </div>
      </div>

      {/* Editor */}
      <div className="flex-1 overflow-auto">
        <div className="mx-auto max-w-[860px] px-8 pb-32 pt-8">
          {/* Title */}
          <textarea
            ref={titleRef}
            value={title}
            onChange={handleTitleChange}
            onKeyDown={handleTitleKeyDown}
            placeholder="无标题"
            rows={1}
            className={cn(
              "w-full resize-none overflow-hidden bg-transparent text-4xl font-bold tracking-tight text-foreground outline-none",
              "placeholder:text-muted-foreground/40",
              "leading-tight"
            )}
          />

          {/* Divider */}
          <div className="my-6 h-px bg-border/50" />

          {/* Content */}
          <textarea
            ref={contentRef}
            value={content}
            onChange={handleContentChange}
            placeholder="开始书写..."
            className={cn(
              "w-full resize-none bg-transparent text-base leading-relaxed text-foreground/90 outline-none",
              "placeholder:text-muted-foreground/40",
              "min-h-[400px]"
            )}
          />
        </div>
      </div>
    </div>
  )
}

// LingNote_front/src/components/note/NoteEditor.vue
<template>
  <div class="note-editor">
    <!-- Save Status -->
    <div class="save-status">
      <div class="save-indicator">
        <span
          class="save-dot"
          :class="{ saving: isSaving, saved: lastSavedAt && !isSaving }"
        />
        <span class="save-text">
          <template v-if="isSaving">保存中...</template>
          <template v-else-if="lastSavedAt">{{ formatLastSaved(lastSavedAt) }}</template>
        </span>
      </div>
    </div>

    <!-- Editor -->
    <div class="editor-scroll">
      <div class="editor-inner">
        <!-- Title -->
        <textarea
          ref="titleRef"
          class="editor-title"
          :value="title"
          @input="onTitleInput"
          @keydown="onTitleKeydown"
          placeholder="无标题"
          rows="1"
        />

        <!-- Divider -->
        <div class="editor-divider" />

        <!-- Content -->
        <textarea
          ref="contentRef"
          class="editor-content"
          :value="content"
          @input="onContentInput"
          placeholder="开始书写..."
        />
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, watch, nextTick } from 'vue'

const props = defineProps({
  title: { type: String, default: '' },
  content: { type: String, default: '' },
  onTitleChange: { type: Function, required: true },
  onContentChange: { type: Function, required: true },
  isSaving: { type: Boolean, default: false },
  lastSavedAt: { type: [Date, null], default: null }
})

const titleRef = ref(null)
const contentRef = ref(null)

const adjustHeight = (el) => {
  if (!el) return
  el.style.height = 'auto'
  el.style.height = `${el.scrollHeight}px`
}

const onTitleInput = (e) => {
  props.onTitleChange(e.target.value)
  nextTick(() => adjustHeight(e.target))
}

const onContentInput = (e) => {
  props.onContentChange(e.target.value)
  nextTick(() => adjustHeight(e.target))
}

const onTitleKeydown = (e) => {
  if (e.key === 'Enter') {
    e.preventDefault()
    contentRef.value?.focus()
  }
}

watch(() => props.title, () => {
  nextTick(() => adjustHeight(titleRef.value))
}, { immediate: true })

watch(() => props.content, () => {
  nextTick(() => adjustHeight(contentRef.value))
}, { immediate: true })

const formatLastSaved = (date) => {
  if (!date) return ''
  const now = new Date()
  const diff = now.getTime() - date.getTime()
  const seconds = Math.floor(diff / 1000)
  const minutes = Math.floor(seconds / 60)
  const hours = Math.floor(minutes / 60)

  if (seconds < 10) return '刚刚保存'
  if (seconds < 60) return `${seconds} 秒前保存`
  if (minutes < 60) return `${minutes} 分钟前保存`
  if (hours < 24) return `${hours} 小时前保存`
  return date.toLocaleDateString('zh-CN', {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}
</script>

<style scoped>
.note-editor {
  display: flex;
  flex-direction: column;
  height: 100%;
}

.save-status {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  height: 40px;
  padding: 0 32px;
}

.save-indicator {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: var(--color-text-muted);
}

.save-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background-color: var(--color-text-muted);
  transition: background-color var(--duration-fast) var(--ease-smooth);
}

.save-dot.saving {
  animation: pulse 1s ease-in-out infinite;
  background-color: var(--color-primary);
}

.save-dot.saved {
  background-color: var(--color-success);
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.4; }
}

.editor-scroll {
  flex: 1;
  overflow-y: auto;
}

.editor-inner {
  max-width: var(--content-width);
  margin: 0 auto;
  padding: 32px 32px 128px;
}

.editor-title {
  width: 100%;
  resize: none;
  overflow: hidden;
  background: transparent;
  font-size: 36px;
  font-weight: 700;
  letter-spacing: -0.02em;
  color: var(--color-text-primary);
  line-height: 1.2;
  outline: none;
}

.editor-title::placeholder {
  color: rgba(31, 41, 55, 0.4);
}

.editor-divider {
  height: 1px;
  margin: 24px 0;
  background-color: var(--color-border-light);
}

.editor-content {
  width: 100%;
  resize: none;
  background: transparent;
  font-size: 16px;
  line-height: 1.75;
  color: rgba(31, 41, 55, 0.9);
  outline: none;
  min-height: 400px;
}

.editor-content::placeholder {
  color: rgba(31, 41, 55, 0.4);
}
</style>
