// LingNote_front/src/components/layout/EditorSidebar.vue
<template>
  <aside class="editor-sidebar" :class="{ collapsed: isCollapsed }">
    <template v-if="isCollapsed">
      <!-- Collapsed state -->
      <div class="collapsed-header">
        <button class="collapsed-logo" @click="backToHome" title="返回首页">
          <span>L</span>
        </button>
        <button class="collapse-toggle" @click="toggleCollapse" title="展开侧边栏">
          <ChevronLeft class="h-4 w-4" />
        </button>
      </div>

      <div class="collapsed-actions">
        <button class="collapsed-create" @click="$emit('create')" title="新建笔记">
          <Plus class="h-4 w-4" />
        </button>
      </div>

      <div class="collapsed-notes">
        <button
          v-for="note in sidebarNotes.slice(0, 10)"
          :key="note.id"
          class="collapsed-note-item"
          :class="{ active: selectedNoteId === note.id }"
          @click="selectNote(note.id)"
          :title="note.title || '无标题'"
        >
          <FileText class="h-4 w-4" />
        </button>
      </div>
    </template>

    <template v-else>
      <!-- Expanded state -->
      <div class="expanded-header">
        <button class="back-btn" @click="backToHome">
          <ChevronLeft class="h-4 w-4" />
          <span>返回</span>
        </button>
        <button class="collapse-btn" @click="toggleCollapse" title="折叠侧边栏">
          <ChevronLeft class="h-4 w-4" />
        </button>
      </div>

      <!-- Search -->
      <div class="sidebar-search">
        <div class="search-wrapper">
          <Search class="search-icon" />
          <input
            class="search-input"
            placeholder="搜索..."
            :value="searchQuery"
            @input="$emit('update:searchQuery', $event.target.value)"
          />
        </div>
      </div>

      <!-- Create -->
      <div class="sidebar-create">
        <button class="create-btn" @click="$emit('create')">
          <Plus class="h-3.5 w-3.5" />
          新建笔记
        </button>
      </div>

      <!-- Notes list -->
      <div class="sidebar-notes">
        <button class="section-header" @click="isExpanded = !isExpanded">
          <ChevronDown class="section-chevron" :class="{ collapsed: !isExpanded }" />
          笔记列表
        </button>

        <div v-if="isExpanded" class="note-items">
          <div
            v-for="note in sidebarNotes"
            :key="note.id"
            class="note-item-wrapper"
          >
            <button
              class="note-item"
              :class="{ active: selectedNoteId === note.id }"
              @click="selectNote(note.id)"
            >
              <FileText class="h-3.5 w-3.5 shrink-0 text-muted" />
              <span class="truncate">{{ note.title || '无标题' }}</span>
            </button>
            <button
              class="note-item-delete"
              @click="$emit('delete', note.id)"
              title="删除笔记"
            >
              <Trash2 class="h-3 w-3" />
            </button>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="sidebar-footer">
        <p class="footer-text">{{ sidebarNotes.length }} 篇笔记</p>
      </div>
    </template>
  </aside>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { Search, Plus, FileText, ChevronLeft, ChevronDown, Trash2 } from 'lucide-vue-next'
import { noteApi } from '@/api/note'

const props = defineProps({
  notes: { type: Array, required: true },
  selectedNoteId: { type: String, default: '' },
  searchQuery: { type: String, default: '' },
  isCollapsed: { type: Boolean, default: false }
})

const emit = defineEmits(['select', 'create', 'update:searchQuery', 'toggleCollapse', 'back', 'delete'])

const isExpanded = ref(true)
const sidebarNotes = ref([])

const loadSidebarNotes = async () => {
  try {
    const data = await noteApi.getAll({
      keyword: props.searchQuery || undefined,
      sortBy: 'updatedAt',
      sortOrder: 'desc'
    })
    sidebarNotes.value = data?.records || []
  } catch (error) {
    console.error('加载侧边栏笔记失败:', error)
  }
}

const selectNote = (id) => emit('select', id)
const toggleCollapse = () => emit('toggleCollapse')
const backToHome = () => emit('back')

onMounted(() => {
  loadSidebarNotes()
})

defineExpose({
  loadSidebarNotes
})
</script>

<style scoped>
.editor-sidebar {
  flex-shrink: 0;
  height: 100vh;
  display: flex;
  flex-direction: column;
  border-right: 1px solid var(--color-border-light);
  background-color: var(--color-background);
  transition: width var(--duration-normal) var(--ease-smooth);
}

.editor-sidebar.collapsed {
  width: 56px;
}

.editor-sidebar:not(.collapsed) {
  width: 224px;
}

/* Collapsed state */
.collapsed-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding: 16px 0;
}

.collapsed-logo {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 8px;
  background-color: var(--color-primary);
  color: #FFFFFF;
  font-size: 14px;
  font-weight: 600;
  transition: background-color var(--duration-normal) var(--ease-smooth);
}

.collapsed-logo:hover {
  background-color: var(--color-primary-hover);
}

.collapse-toggle {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 8px;
  background: none;
  color: var(--color-text-secondary);
  transition: all var(--duration-fast) var(--ease-smooth);
}

.collapse-toggle:hover {
  background-color: rgba(15, 23, 42, 0.04);
  color: var(--color-text-primary);
}

.collapse-toggle svg {
  transform: rotate(180deg);
}

.collapsed-actions {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  padding: 0 8px;
}

.collapsed-create {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 8px;
  background: none;
  color: var(--color-primary);
  transition: all var(--duration-fast) var(--ease-smooth);
}

.collapsed-create:hover {
  background-color: rgba(79, 124, 255, 0.1);
}

.collapsed-notes {
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 4px;
  padding: 8px;
}

.collapsed-note-item {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 32px;
  height: 32px;
  border-radius: 6px;
  background: none;
  color: var(--color-text-muted);
  transition: all var(--duration-fast) var(--ease-smooth);
}

.collapsed-note-item:hover {
  background-color: rgba(15, 23, 42, 0.04);
  color: var(--color-text-primary);
}

.collapsed-note-item.active {
  background-color: rgba(79, 124, 255, 0.08);
  color: var(--color-text-primary);
}

/* Expanded state */
.expanded-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px;
}

.back-btn {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px 8px;
  border-radius: 6px;
  background: none;
  color: var(--color-text-secondary);
  font-size: 13px;
  transition: all var(--duration-fast) var(--ease-smooth);
}

.back-btn:hover {
  background-color: rgba(15, 23, 42, 0.04);
  color: var(--color-text-primary);
}

.collapse-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: 6px;
  background: none;
  color: var(--color-text-secondary);
  transition: all var(--duration-fast) var(--ease-smooth);
}

.collapse-btn:hover {
  background-color: rgba(15, 23, 42, 0.04);
  color: var(--color-text-primary);
}

.sidebar-search {
  padding: 0 12px 8px;
}

.search-wrapper {
  position: relative;
}

.search-icon {
  position: absolute;
  left: 10px;
  top: 50%;
  transform: translateY(-50%);
  width: 14px;
  height: 14px;
  color: var(--color-text-muted);
}

.search-input {
  width: 100%;
  height: 32px;
  padding: 0 10px 0 30px;
  border: 1px solid transparent;
  border-radius: 8px;
  background-color: rgba(15, 23, 42, 0.04);
  font-size: 13px;
  color: var(--color-text-primary);
  transition: all var(--duration-normal) var(--ease-smooth);
}

.search-input:focus {
  background-color: var(--color-card);
  border-color: var(--color-border);
  box-shadow: 0 0 0 3px rgba(79, 124, 255, 0.1);
}

.search-input::placeholder {
  color: var(--color-text-muted);
}

.sidebar-create {
  padding: 0 12px 12px;
}

.create-btn {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  height: 32px;
  padding: 0 12px;
  border-radius: 8px;
  background-color: rgba(79, 124, 255, 0.1);
  color: var(--color-primary);
  font-size: 13px;
  font-weight: 500;
  transition: background-color var(--duration-normal) var(--ease-smooth);
}

.create-btn:hover {
  background-color: rgba(79, 124, 255, 0.15);
}

.sidebar-notes {
  flex: 1;
  overflow-y: auto;
  padding: 0 12px;
}

.section-header {
  display: flex;
  align-items: center;
  gap: 6px;
  width: 100%;
  padding: 4px 6px;
  font-size: 12px;
  font-weight: 500;
  color: var(--color-text-secondary);
  background: none;
  transition: color var(--duration-fast) var(--ease-smooth);
}

.section-header:hover {
  color: var(--color-text-primary);
}

.section-chevron {
  width: 12px;
  height: 12px;
  transition: transform var(--duration-normal) var(--ease-smooth);
}

.section-chevron.collapsed {
  transform: rotate(-90deg);
}

.note-items {
  margin-top: 4px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.note-item-wrapper {
  position: relative;
  display: flex;
  align-items: center;
}

.note-item-wrapper:hover .note-item-delete {
  opacity: 1;
  visibility: visible;
}

.note-item {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
  min-width: 0;
  padding: 6px 8px;
  border-radius: 6px;
  font-size: 13px;
  color: rgba(31, 41, 55, 0.8);
  background: none;
  text-align: left;
  transition: all var(--duration-fast) var(--ease-smooth);
}

.note-item:hover {
  background-color: rgba(15, 23, 42, 0.04);
}

.note-item.active {
  background-color: rgba(79, 124, 255, 0.08);
  color: var(--color-text-primary);
}

.note-item-delete {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: 6px;
  border: none;
  background: none;
  color: var(--color-text-muted);
  opacity: 0;
  visibility: hidden;
  cursor: pointer;
  transition: all var(--duration-fast) var(--ease-smooth);
  flex-shrink: 0;
  position: absolute;
  right: 4px;
}

.note-item-delete:hover {
  background-color: rgba(239, 68, 68, 0.1);
  color: var(--color-error);
}

.sidebar-footer {
  border-top: 1px solid var(--color-border-light);
  padding: 10px 16px;
}

.footer-text {
  font-size: 12px;
  color: var(--color-text-muted);
}
</style>

// LingNote_front/example/lingnote_front/components/editor-sidebar.tsx
"use client"

import { useState } from "react"
import { Search, Plus, FileText, ChevronLeft, ChevronDown } from "lucide-react"
import { cn } from "@/lib/utils"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"

interface Note {
  id: string
  title: string
  updatedAt: string
}

interface EditorSidebarProps {
  notes: Note[]
  selectedNoteId?: string
  onSelectNote: (id: string) => void
  onCreateNote: () => void
  onSearch: (query: string) => void
  searchQuery: string
  isCollapsed: boolean
  onToggleCollapse: () => void
  onBackToHome: () => void
}

export function EditorSidebar({
  notes,
  selectedNoteId,
  onSelectNote,
  onCreateNote,
  onSearch,
  searchQuery,
  isCollapsed,
  onToggleCollapse,
  onBackToHome,
}: EditorSidebarProps) {
  const [isExpanded, setIsExpanded] = useState(true)

  if (isCollapsed) {
    return (
      <TooltipProvider delayDuration={0}>
        <aside className="flex h-full w-14 flex-col border-r border-border bg-sidebar">
          {/* Collapsed Header */}
          <div className="flex flex-col items-center gap-2 py-4">
            <Tooltip>
              <TooltipTrigger asChild>
                <button
                  onClick={onBackToHome}
                  className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground transition-colors hover:bg-primary/90"
                >
                  <span className="text-sm font-semibold">L</span>
                </button>
              </TooltipTrigger>
              <TooltipContent side="right">返回首页</TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={onToggleCollapse}
                  className="text-muted-foreground hover:text-foreground"
                >
                  <ChevronLeft className="h-4 w-4 rotate-180" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="right">展开侧边栏</TooltipContent>
            </Tooltip>
          </div>

          {/* Collapsed Actions */}
          <div className="flex flex-col items-center gap-1 px-2">
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={onCreateNote}
                  className="text-primary hover:bg-primary/10"
                >
                  <Plus className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="right">新建笔记</TooltipContent>
            </Tooltip>
          </div>

          {/* Collapsed Notes */}
          <ScrollArea className="flex-1 py-2">
            <div className="flex flex-col items-center gap-0.5 px-2">
              {notes.slice(0, 10).map((note) => (
                <Tooltip key={note.id}>
                  <TooltipTrigger asChild>
                    <button
                      onClick={() => onSelectNote(note.id)}
                      className={cn(
                        "flex h-8 w-8 items-center justify-center rounded-md transition-colors",
                        selectedNoteId === note.id
                          ? "bg-accent text-accent-foreground"
                          : "text-muted-foreground hover:bg-muted hover:text-foreground"
                      )}
                    >
                      <FileText className="h-4 w-4" />
                    </button>
                  </TooltipTrigger>
                  <TooltipContent side="right">
                    {note.title || "无标题"}
                  </TooltipContent>
                </Tooltip>
              ))}
            </div>
          </ScrollArea>
        </aside>
      </TooltipProvider>
    )
  }

  return (
    <aside className="flex h-full w-56 flex-col border-r border-border bg-sidebar">
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-3">
        <button
          onClick={onBackToHome}
          className="flex items-center gap-2 rounded-md px-2 py-1 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
        >
          <ChevronLeft className="h-4 w-4" />
          <span className="text-sm">返回</span>
        </button>
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={onToggleCollapse}
          className="text-muted-foreground hover:text-foreground"
        >
          <ChevronLeft className="h-4 w-4" />
        </Button>
      </div>

      {/* Search */}
      <div className="px-3 pb-2">
        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="搜索..."
            value={searchQuery}
            onChange={(e) => onSearch(e.target.value)}
            className="h-8 border-transparent bg-muted pl-8 text-sm placeholder:text-muted-foreground/60 focus-visible:border-border focus-visible:ring-1 focus-visible:ring-ring/20"
          />
        </div>
      </div>

      {/* Create Note */}
      <div className="px-3 pb-3">
        <Button
          onClick={onCreateNote}
          variant="ghost"
          size="sm"
          className="h-8 w-full justify-start gap-2 bg-primary/10 text-primary hover:bg-primary/15"
        >
          <Plus className="h-3.5 w-3.5" />
          新建笔记
        </Button>
      </div>

      {/* Notes List */}
      <ScrollArea className="flex-1 px-3">
        <div>
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="flex w-full items-center gap-1.5 px-1.5 py-1 text-xs font-medium text-muted-foreground hover:text-foreground"
          >
            <ChevronDown
              className={cn(
                "h-3 w-3 transition-transform",
                !isExpanded && "-rotate-90"
              )}
            />
            笔记列表
          </button>

          {isExpanded && (
            <div className="mt-1 space-y-0.5">
              {notes.map((note) => (
                <button
                  key={note.id}
                  onClick={() => onSelectNote(note.id)}
                  className={cn(
                    "flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-sm transition-colors",
                    selectedNoteId === note.id
                      ? "bg-accent text-accent-foreground"
                      : "text-foreground/80 hover:bg-muted"
                  )}
                >
                  <FileText className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
                  <span className="truncate text-left">
                    {note.title || "无标题"}
                  </span>
                </button>
              ))}
            </div>
          )}
        </div>
      </ScrollArea>

      {/* Footer */}
      <div className="border-t border-border px-4 py-2.5">
        <p className="text-xs text-muted-foreground">{notes.length} 篇笔记</p>
      </div>
    </aside>
  )
}
